// ---------------------- Clase Paginas ----------------------
package tarea4pspsolucion;

import java.util.Random;

public class Paginas {

    public static final String html_index = "<!DOCTYPE html>"
            + "<html lang='es'>"
            + "<head>"
            + "<meta charset='UTF-8'>"
            + "<title>Inicio</title>"
            + "<link rel='icon' href='data:,'/>"
            + "<style>"
            + "body {"
            + "  font-family: Arial, sans-serif;"
            + "  background: linear-gradient(135deg, #74ebd5, #9face6);"
            + "  display: flex;"
            + "  justify-content: center;"
            + "  align-items: center;"
            + "  height: 100vh;"
            + "  margin: 0;"
            + "}"
            + ".container {"
            + "  background: white;"
            + "  padding: 40px;"
            + "  border-radius: 15px;"
            + "  box-shadow: 0 8px 16px rgba(0,0,0,0.2);"
            + "  width: 400px;"
            + "  text-align: center;"
            + "}"
            + "ul {"
            + "  list-style: none;"
            + "  padding: 0;"
            + "}"
            + "li {"
            + "  margin: 10px 0;"
            + "}"
            + "a {"
            + "  text-decoration: none;"
            + "  color: #4CAF50;"
            + "  font-weight: bold;"
            + "}"
            + ".boton-secundario {"
            + "  background-color: #f44336;"
            + "  color: white;"
            + "  padding: 12px;"
            + "  margin-top: 20px;"
            + "  border: none;"
            + "  border-radius: 8px;"
            + "  cursor: pointer;"
            + "  font-size: 16px;"
            + "  text-decoration: none;"
            + "  display: inline-block;"
            + "  width: 100%;"
            + "  box-sizing: border-box;"
            + "  text-align: center;"
            + "  transition: background-color 0.3s ease;"
            + "}"
            + ".boton-secundario:hover {"
            + "  background-color: #d32f2f;"
            + "}"
            + "</style>"
            + "</head>"
            + "<body>"
            + "<div class='container'>"
            + "<h1>Bienvenido al Servidor de Juegos</h1>"
            + "<ul>"
            + "<li><a href='/adivina'>Adivina el Número</a></li>"
            + "<li><a href='/dados'>Lanza Dados</a></li>"
            + "<li><a href='/ppt'>Piedra, Papel o Tijera</a></li>"
            + "</ul>"
            + "<a href='/logout' class='boton-secundario'>Cerrar sesión</a>"
            + "</div>"
            + "</body>"
            + "</html>";

    public static final String html_noEncontrado = "<!DOCTYPE html>"
            + "<html lang='es'>"
            + "<head>"
            + "<meta charset='UTF-8'>"
            + "<title>Error 404</title>"
            + "<link rel='icon' href='data:,'/>"
            + "<style>"
            + "body {"
            + "  font-family: Arial, sans-serif;"
            + "  background: linear-gradient(135deg, #ffecd2, #fcb69f);"
            + "  display: flex;"
            + "  justify-content: center;"
            + "  align-items: center;"
            + "  height: 100vh;"
            + "  margin: 0;"
            + "}"
            + ".container {"
            + "  background: white;"
            + "  padding: 40px;"
            + "  border-radius: 15px;"
            + "  box-shadow: 0 8px 16px rgba(0,0,0,0.2);"
            + "  text-align: center;"
            + "}"
            + "</style>"
            + "</head>"
            + "<body>"
            + "<div class='container'>"
            + "<h1>404 Página No Encontrada</h1>"
            + "<p>La página solicitada no existe.</p>"
            + "</div>"
            + "</body>"
            + "</html>";

    public static final String html_LoginRegistro(String resultado) {
        return "<!DOCTYPE html>"
                + "<html lang='es'>"
                + "<head>"
                + "<meta charset='UTF-8'>"
                + "<title>Login y Registro</title>"
                + "<style>"
                + "body {"
                + "    font-family: Arial, sans-serif;"
                + "    background: linear-gradient(135deg, #74ebd5, #9face6);"
                + "    display: flex;"
                + "    justify-content: center;"
                + "    align-items: center;"
                + "    height: 100vh;"
                + "    margin: 0;"
                + "}"
                + ".container {"
                + "    background: white;"
                + "    padding: 40px;"
                + "    border-radius: 15px;"
                + "    box-shadow: 0 8px 16px rgba(0,0,0,0.2);"
                + "    width: 400px;"
                + "}"
                + "h2 {"
                + "    text-align: center;"
                + "    color: #333;"
                + "}"
                + "form {"
                + "    display: flex;"
                + "    flex-direction: column;"
                + "    margin-top: 20px;"
                + "}"
                + "input {"
                + "    padding: 12px;"
                + "    margin: 8px 0;"
                + "    border: 1px solid #ccc;"
                + "    border-radius: 8px;"
                + "    font-size: 16px;"
                + "}"
                + "button {"
                + "    background-color: #4CAF50;"
                + "    color: white;"
                + "    padding: 12px;"
                + "    border: none;"
                + "    border-radius: 8px;"
                + "    cursor: pointer;"
                + "    font-size: 16px;"
                + "    transition: background-color 0.3s ease;"
                + "}"
                + "button:hover {"
                + "    background-color: #45a049;"
                + "}"
                + ".section {"
                + "    margin-bottom: 40px;"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div class='container'>"
                + "  <div class='section'>"
                + resultado
                + "    <h2>Iniciar Sesión</h2>"
                + "    <form action='/login' method='post'>"
                + "      <input type='email' name='email' placeholder='Correo electrónico' required>"
                + "      <input type='password' name='password' placeholder='Contraseña' required>"
                + "      <button type='submit'>Entrar</button>"
                + "    </form>"
                + "  </div>"
                + "  <div class='section'>"
                + "    <h2>Registrarse</h2>"
                + "    <form action='/registro' method='post'>"
                + "      <input type='email' name='email' placeholder='Correo electrónico' required>"
                + "      <input type='password' name='password' placeholder='Contraseña' required>"
                + "      <button type='submit'>Registrarse</button>"
                + "    </form>"
                + "  </div>"
                + "</div>"
                + "</body>"
                + "</html>";
    }

    public static String generarHtmlAdivina(String resultado) {
        return "<!DOCTYPE html>"
                + "<html lang='es'>"
                + "<head>"
                + "<meta charset='UTF-8'>"
                + "<title>Adivina el Número</title>"
                + "<link rel='icon' href='data:,'/>"
                + "<style>"
                + "body {"
                + "  font-family: Arial, sans-serif;"
                + "  background: linear-gradient(135deg, #74ebd5, #9face6);"
                + "  display: flex;"
                + "  justify-content: center;"
                + "  align-items: center;"
                + "  height: 100vh;"
                + "  margin: 0;"
                + "}"
                + ".container {"
                + "  background: white;"
                + "  padding: 40px;"
                + "  border-radius: 15px;"
                + "  box-shadow: 0 8px 16px rgba(0,0,0,0.2);"
                + "  width: 400px;"
                + "  text-align: center;"
                + "}"
                + "input, button {"
                + "  width: 100%;"
                + "  padding: 12px;"
                + "  margin-top: 10px;"
                + "  border-radius: 8px;"
                + "  border: 1px solid #ccc;"
                + "  font-size: 16px;"
                + "  box-sizing: border-box;"
                + "}"
                + "button {"
                + "  background-color: #4CAF50;"
                + "  color: white;"
                + "  border: none;"
                + "  cursor: pointer;"
                + "}"
                + "button:hover {"
                + "  background-color: #45a049;"
                + "}"
                + ".boton-secundario {"
                + "  background-color: #f44336;"
                + "  color: white;"
                + "  padding: 12px;"
                + "  margin-top: 20px;"
                + "  border: none;"
                + "  border-radius: 8px;"
                + "  cursor: pointer;"
                + "  font-size: 16px;"
                + "  text-decoration: none;"
                + "  display: inline-block;"
                + "  width: 100%;"
                + "  box-sizing: border-box;"
                + "  text-align: center;"
                + "  transition: background-color 0.3s ease;"
                + "}"
                + ".boton-secundario:hover {"
                + "  background-color: #d32f2f;"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div class='container'>"
                + "<h1>¡Adivina el Número!</h1>"
                + "<form action='/adivina' method='POST'>"
                + "<label for='numero'>Introduce un número del 1 al 100:</label>"
                + "<input type='number' id='numero' name='numero' min='1' max='100' required>"
                + "<button type='submit'>Enviar</button>"
                + "</form>"
                + resultado
                + "<a href='/' class='boton-secundario'>Volver al Inicio</a>"
                + "<a href='/logout' class='boton-secundario'>Cerrar sesión</a>"
                + "</div>"
                + "</body>"
                + "</html>";
    }

    public static String generarHtmlPpt(String resultado) {
        return "<!DOCTYPE html>"
                + "<html lang='es'>"
                + "<head>"
                + "<meta charset='UTF-8'>"
                + "<title>Piedra, Papel o Tijera</title>"
                + "<link rel='icon' href='data:,'/>"
                + "<style>"
                + "body {"
                + "  font-family: Arial, sans-serif;"
                + "  background: linear-gradient(135deg, #74ebd5, #9face6);"
                + "  display: flex;"
                + "  justify-content: center;"
                + "  align-items: center;"
                + "  height: 100vh;"
                + "  margin: 0;"
                + "}"
                + ".container {"
                + "  background: white;"
                + "  padding: 40px;"
                + "  border-radius: 15px;"
                + "  box-shadow: 0 8px 16px rgba(0,0,0,0.2);"
                + "  width: 400px;"
                + "  text-align: center;"
                + "}"
                + "button {"
                + "  width: 100%;"
                + "  padding: 12px;"
                + "  margin-top: 10px;"
                + "  border-radius: 8px;"
                + "  border: none;"
                + "  background-color: #4CAF50;"
                + "  color: white;"
                + "  font-size: 16px;"
                + "  cursor: pointer;"
                + "}"
                + "button:hover {"
                + "  background-color: #45a049;"
                + "}"
                + ".boton-secundario {"
                + "  background-color: #f44336;"
                + "  color: white;"
                + "  padding: 12px;"
                + "  margin-top: 20px;"
                + "  border: none;"
                + "  border-radius: 8px;"
                + "  cursor: pointer;"
                + "  font-size: 16px;"
                + "  text-decoration: none;"
                + "  display: inline-block;"
                + "  width: 100%;"
                + "  box-sizing: border-box;"
                + "  text-align: center;"
                + "  transition: background-color 0.3s ease;"
                + "}"
                + ".boton-secundario:hover {"
                + "  background-color: #d32f2f;"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div class='container'>"
                + "<h1>¡Juega a Piedra, Papel o Tijera!</h1>"
                + "<form action='/ppt' method='POST'>"
                + "<button name='opcion' value='Piedra'>Piedra</button>"
                + "<button name='opcion' value='Papel'>Papel</button>"
                + "<button name='opcion' value='Tijeras'>Tijeras</button>"
                + "</form>"
                + resultado
                + "<a href='/' class='boton-secundario'>Volver al Inicio</a>"
                + "<a href='/logout' class='boton-secundario'>Cerrar sesión</a>"
                + "</div>"
                + "</body>"
                + "</html>";
    }

    public static String generarHtmlDados(String resultado) {
        Random random = new Random();
        int dadoCliente = random.nextInt(6) + 1;
        return "<!DOCTYPE html>"
                + "<html lang='es'>"
                + "<head>"
                + "<meta charset='UTF-8'>"
                + "<title>Lanza Dados</title>"
                + "<link rel='icon' href='data:,'/>"
                + "<style>"
                + "body {"
                + "  font-family: Arial, sans-serif;"
                + "  background: linear-gradient(135deg, #74ebd5, #9face6);"
                + "  display: flex;"
                + "  justify-content: center;"
                + "  align-items: center;"
                + "  height: 100vh;"
                + "  margin: 0;"
                + "}"
                + ".container {"
                + "  background: white;"
                + "  padding: 40px;"
                + "  border-radius: 15px;"
                + "  box-shadow: 0 8px 16px rgba(0,0,0,0.2);"
                + "  width: 400px;"
                + "  text-align: center;"
                + "}"
                + "button {"
                + "  padding: 12px 24px;"
                + "  font-size: 16px;"
                + "  border-radius: 8px;"
                + "  background-color: #4CAF50;"
                + "  color: white;"
                + "  border: none;"
                + "  cursor: pointer;"
                + "}"
                + "button:hover {"
                + "  background-color: #45a049;"
                + "}"
                + ".boton-secundario {"
                + "  background-color: #f44336;"
                + "  color: white;"
                + "  padding: 12px;"
                + "  margin-top: 20px;"
                + "  border: none;"
                + "  border-radius: 8px;"
                + "  cursor: pointer;"
                + "  font-size: 16px;"
                + "  text-decoration: none;"
                + "  display: inline-block;"
                + "  width: 100%;"
                + "  box-sizing: border-box;"
                + "  text-align: center;"
                + "  transition: background-color 0.3s ease;"
                + "}"
                + ".boton-secundario:hover {"
                + "  background-color: #d32f2f;"
                + "}"
                + "</style>"
                + "</head>"
                + "<body>"
                + "<div class='container'>"
                + "<h1>¡Lanza Dados!</h1>"
                + "<form action='/dados' method='POST'>"
                + "<button name='lanzar' value='" + dadoCliente + "'>Lanzar Dados</button>"
                + "</form>"
                + resultado
                + "<a href='/' class='boton-secundario'>Volver al Inicio</a>"
                + "<a href='/logout' class='boton-secundario'>Cerrar sesión</a>"
                + "</div>"
                + "</body>"
                + "</html>";
    }
}
