/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import modelo.GestionBD;



/**
 *
 * @author Usuario
 */
public class InitialFrame extends javax.swing.JFrame {

    /**
     * Creates new form InitalFrame
     */
    public InitialFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_extraerColecciones = new javax.swing.JButton();
        jButton_consulta2a = new javax.swing.JButton();
        jButton_consulta2b = new javax.swing.JButton();
        jButton_consulta2c = new javax.swing.JButton();
        jButton_consulta2d = new javax.swing.JButton();
        jButton_consulta3a = new javax.swing.JButton();
        jButton_consulta3b = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane_resultados = new javax.swing.JEditorPane();
        jButton_consulta3c = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton_extraerColecciones.setText("Extraer Colecciones");
        jButton_extraerColecciones.setActionCommand("");
        jButton_extraerColecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_extraerColeccionesActionPerformed(evt);
            }
        });

        jButton_consulta2a.setText("Matrícula Vehículos Matriculados en 2024");
        jButton_consulta2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_consulta2aActionPerformed(evt);
            }
        });

        jButton_consulta2b.setText("Marca-Modelo Vehículos < 75000 KM");
        jButton_consulta2b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_consulta2bActionPerformed(evt);
            }
        });

        jButton_consulta2c.setText("Nombre-Apellidos Propietarios de Golfs");
        jButton_consulta2c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_consulta2cActionPerformed(evt);
            }
        });

        jButton_consulta2d.setText("Nombre-Apellidos de Mecánicos");
        jButton_consulta2d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_consulta2dActionPerformed(evt);
            }
        });

        jButton_consulta3a.setText("Cambiar a 110000 los KM del vehículo 6666FFF");
        jButton_consulta3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_consulta3aActionPerformed(evt);
            }
        });

        jButton_consulta3b.setText("Cambiar nodo \"kilometros\" a \"kms\"");
        jButton_consulta3b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_consulta3bActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jEditorPane_resultados);

        jButton_consulta3c.setText("Insertar Nueva Reparación");
        jButton_consulta3c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_consulta3cActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_consulta2a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_extraerColecciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_consulta2b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_consulta2c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_consulta2d, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_consulta3a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_consulta3b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_consulta3c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_extraerColecciones)
                        .addGap(14, 14, 14)
                        .addComponent(jButton_consulta2a)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_consulta2b)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_consulta2c)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_consulta2d)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_consulta3a)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_consulta3b)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_consulta3c)
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Cuando se cierra la ventana se realiza primero la desconexión de la base de datos y se muestra mensaje
     * informativo de la acción
     * @param evt 
     */    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, GestionBD.desconectarBD());
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButton_extraerColeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_extraerColeccionesActionPerformed
        // TODO add your handling code here:
        if (GestionBD.extraeColecciones())
            JOptionPane.showMessageDialog(null, "Las colecciones se han extraido correctamente");
        else
            JOptionPane.showMessageDialog(null, "Se ha producido algún error al extraer las colecciones");

    }//GEN-LAST:event_jButton_extraerColeccionesActionPerformed

    private void jButton_consulta2bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_consulta2bActionPerformed
        // TODO add your handling code here:
        jEditorPane_resultados.setText(GestionBD.ejecutarConsultaDeArchivo("consulta2b.xq"));
    }//GEN-LAST:event_jButton_consulta2bActionPerformed

    private void jButton_consulta2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_consulta2aActionPerformed
        // TODO add your handling code here:
        jEditorPane_resultados.setText(GestionBD.ejecutarConsultaDeArchivo("consulta2a.xq"));
       
    }//GEN-LAST:event_jButton_consulta2aActionPerformed

    private void jButton_consulta2cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_consulta2cActionPerformed
        // TODO add your handling code here:
        jEditorPane_resultados.setText(GestionBD.ejecutarConsultaDeArchivo("consulta2c.xq"));
    }//GEN-LAST:event_jButton_consulta2cActionPerformed

    private void jButton_consulta2dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_consulta2dActionPerformed
        // TODO add your handling code here:
        jEditorPane_resultados.setText(GestionBD.ejecutarConsultaDeArchivo("consulta2d.xq"));
    }//GEN-LAST:event_jButton_consulta2dActionPerformed

    private void jButton_consulta3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_consulta3aActionPerformed
        // TODO add your handling code here:
        GestionBD.ejecutarConsultaDeArchivo("consulta3a.xq");
        jEditorPane_resultados.setText(GestionBD.mostrarTodo());
    }//GEN-LAST:event_jButton_consulta3aActionPerformed

    private void jButton_consulta3bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_consulta3bActionPerformed
        // TODO add your handling code here:
        GestionBD.ejecutarConsultaDeArchivo("consulta3b.xq");
        jEditorPane_resultados.setText(GestionBD.mostrarTodo());
    }//GEN-LAST:event_jButton_consulta3bActionPerformed

    private void jButton_consulta3cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_consulta3cActionPerformed
        // TODO add your handling code here:
        GestionBD.ejecutarConsultaDeArchivo("consulta3c.xq");
        jEditorPane_resultados.setText(GestionBD.mostrarTodo());
    }//GEN-LAST:event_jButton_consulta3cActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitialFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitialFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitialFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitialFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InitialFrame().setVisible(true);
                //conectar con la base de datos y mostrar un mensaje informando de si la conexión ha sido exitosa    
                JOptionPane.showMessageDialog(null, GestionBD.conectarBD());
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_consulta2a;
    private javax.swing.JButton jButton_consulta2b;
    private javax.swing.JButton jButton_consulta2c;
    private javax.swing.JButton jButton_consulta2d;
    private javax.swing.JButton jButton_consulta3a;
    private javax.swing.JButton jButton_consulta3b;
    private javax.swing.JButton jButton_consulta3c;
    private javax.swing.JButton jButton_extraerColecciones;
    private javax.swing.JEditorPane jEditorPane_resultados;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
