/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebabeans_ad6;
import crearbeans_ad6.ProductoBean;
import crearbeans_ad6.ProductoBean.AddProductoEvent;
import crearbeans_ad6.ProductoBean.BDModificadaEvent;
import crearbeans_ad6.ProductoBean.BDModificadaListener;
import crearbeans_ad6.ProductoBean.DeleteProductoEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class VentanaInicial extends javax.swing.JFrame implements BDModificadaListener{
    
    
    ProductoBean pb;
    /**
     * Creates new form VentanaInicial
     */
    public VentanaInicial() {
        initComponents();
        pb = new ProductoBean();
        pb.addBDModificadaListener( (BDModificadaListener)this );
        pb.removeBDModificadaListener((BDModificadaListener)this);
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_productos = new javax.swing.JTable();
        jButton_altaProducto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTF_ref = new javax.swing.JTextField();
        jTF_nom = new javax.swing.JTextField();
        jTF_des = new javax.swing.JTextField();
        jTF_pre = new javax.swing.JTextField();
        jTF_descu = new javax.swing.JTextField();
        jButton_eliminarProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NUMERO", "REFERENCIA", "NOMBRE", "DESCRIPCION", "PRECIO", "DESCUENTO"
            }
        ));
        jScrollPane1.setViewportView(jTable_productos);

        jButton_altaProducto.setText("AÑADIR PRODUCTO");
        jButton_altaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_altaProductoActionPerformed(evt);
            }
        });

        jLabel1.setText("Referencia");

        jLabel2.setText("Nombre");

        jLabel3.setText("Descripción");

        jLabel4.setText("Precio");

        jLabel5.setText("Descuento");

        jButton_eliminarProducto.setText("ELIMINAR PRODUCTO");
        jButton_eliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(jButton_altaProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_eliminarProducto)
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTF_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTF_ref, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTF_descu, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTF_pre, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jTF_des, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTF_ref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTF_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTF_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTF_pre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTF_descu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_altaProducto)
                    .addComponent(jButton_eliminarProducto))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_altaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_altaProductoActionPerformed
        // TODO add your handling code here:
        if (jTF_ref.getText().isEmpty() || jTF_nom.getText().isEmpty() || jTF_des.getText().isEmpty() || jTF_pre.getText().isEmpty() || jTF_descu.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Todos los campos deben estar rellenos");
        else {
            try{
                Float precio=Float.parseFloat(jTF_pre.getText());
                Float descuento=Float.parseFloat(jTF_descu.getText());
                 
                pb.setReferencia(jTF_ref.getText());
                pb.setNombre(jTF_nom.getText());
                pb.setDescripcion(jTF_des.getText());
                pb.setPrecio(precio);
                pb.setDescuento(descuento);
                try {
                    if(!pb.existeProducto())
                        pb.addProducto();
                    else
                      JOptionPane.showMessageDialog(null, "Ya existe un producto con esa referencia");  
                        
                } 
                catch (ClassNotFoundException ex) {
                    Logger.getLogger(VentanaInicial.class.getName()).log(Level.SEVERE, null, ex);
                }  
                limpiarCampos();
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Precio y descuento deben ser un valores númericos que pueden ser decimales");    
            }
            
        }
        
    }//GEN-LAST:event_jButton_altaProductoActionPerformed

    private void jButton_eliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarProductoActionPerformed
        // TODO add your handling code here:
        if (jTF_ref.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Para borrar un producto debe indicar su referencia en el campo referencia");
        else {
            pb.setReferencia(jTF_ref.getText());
            try {
                if(pb.existeProducto())
                    pb.deleteProducto();
                else
                    JOptionPane.showMessageDialog(null, "No existe un producto con esa referencia");  
            } 
            catch (ClassNotFoundException ex) {
                Logger.getLogger(VentanaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        limpiarCampos();
    }//GEN-LAST:event_jButton_eliminarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicial().setVisible(true);
            }
        });
    }
    /***************************************************************************
     * Método que rellena la tabla con los productos que nos devuelve ProductoBeans
     * a través de su método seleccionarFila, y los va listando añadiendo un número
     * de producto en la primera columna de la tabla.
     */
    private void actualizarTabla(){
        
        DefaultTableModel modelo = (DefaultTableModel) jTable_productos.getModel();
        modelo.setNumRows(0);
        int i=0;
        while(i<pb.numFilas()){
            pb.seleccionarFila(i);
            Object[] fila = {++i, 
                             pb.getReferencia(), 
                             pb.getNombre(), 
                             pb.getDescripcion(),
                             pb.getPrecio(), 
                             pb.getDescuento()};  // Datos según las columnas
            modelo.addRow(fila);
        }
    }
    /***************************************************************************
     * Método que borra todos los campos de texto del formulario de la ventana
     */
    private void limpiarCampos(){
        jTF_ref.setText("");
        jTF_nom.setText("");
        jTF_des.setText("");
        jTF_pre.setText("");
        jTF_descu.setText("");        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_altaProducto;
    private javax.swing.JButton jButton_eliminarProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_des;
    private javax.swing.JTextField jTF_descu;
    private javax.swing.JTextField jTF_nom;
    private javax.swing.JTextField jTF_pre;
    private javax.swing.JTextField jTF_ref;
    private javax.swing.JTable jTable_productos;
    // End of variables declaration//GEN-END:variables

    /**
     * Captura el evento de modificación de base de datos, actualizando el contenido
     * de la tabla de productos y mostrando un mensaje informativo en función de cual
     * ha sido el evento producido.
     * @param ev 
     */
    @Override
    public void capturarBDModificada(BDModificadaEvent ev) {
        actualizarTabla();
        if (ev instanceof AddProductoEvent) 
            JOptionPane.showMessageDialog(null, "Se ha añadido un nuevo producto correctamente");
        if (ev instanceof DeleteProductoEvent) 
            JOptionPane.showMessageDialog(null, "Se ha eliminado el producto correctamente");
    }
}
    
