/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;


import com.db4o.ObjectSet;
import javax.swing.JOptionPane;
import static interfaz.initialFrame.actualizarTodosAutores;
import java.awt.event.WindowEvent;
import java.awt.event.WindowFocusListener;
import javax.swing.table.DefaultTableModel;
import modelo.Autor;
import modelo.gestionBD;
import static modelo.gestionBD.obtenerTodosAutores;

/**
 *
 * @author Usuario
 */
public class addCancionFrame extends javax.swing.JFrame {

    /**
     * Creates new form addCancionFrame
     */
    public addCancionFrame() {
        initComponents();
        
        /* controlar cuando la ventana principal tiene el foco */    
        this.addWindowFocusListener(new WindowFocusListener() {
            @Override
            public void windowGainedFocus(WindowEvent e) {
                //System.out.println("Ventana principal recuperó el foco");
                // Actualizar datos, refrescar tablas, etc.
                actualizarComboAutores();
            }

            @Override
            public void windowLostFocus(WindowEvent e) {
                // Opcional: acciones cuando se pierde el foco
                // System.out.println("Ventana principal perdió el foco");
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_añadir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTF_ide = new javax.swing.JTextField();
        jTF_tit = new javax.swing.JTextField();
        jTF_dur = new javax.swing.JTextField();
        jTF_año = new javax.swing.JTextField();
        jTF_gen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCombo_autores = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva Canción");
        setBackground(new java.awt.Color(255, 255, 255));

        jButton_añadir.setText("Añadir");
        jButton_añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_añadirActionPerformed(evt);
            }
        });

        jLabel1.setText("Identificador");

        jTF_ide.setName(""); // NOI18N
        jTF_ide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_ideActionPerformed(evt);
            }
        });

        jTF_gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_genActionPerformed(evt);
            }
        });

        jLabel2.setText("Titulo");

        jLabel3.setText("Duración");

        jLabel4.setText("Año Creación");

        jLabel5.setText("Genero");

        jLabel6.setText("Autor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCombo_autores, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_añadir)
                    .addComponent(jTF_ide, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_dur, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_año, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_gen, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_tit, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTF_ide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTF_tit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTF_dur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(jTF_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTF_gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCombo_autores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_añadir)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_añadirActionPerformed
        // TODO add your handling code here:
         
        //validar que los datos son correctos
        String autorSeleccionado = (String) jCombo_autores.getSelectedItem();
        if (!(autorSeleccionado != null && !autorSeleccionado.isEmpty())){
            JOptionPane.showMessageDialog(null, "No es posible añadir una canción sin indicar su autor (añadir primero autor)");
        }
        else if (jTF_ide.getText().isEmpty() || jTF_tit.getText().isEmpty() || jTF_dur.getText().isEmpty() || jTF_año.getText().isEmpty() || jTF_gen.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Todos los campos deben estar rellenos");
        }
        else if (!esDecimal(jTF_dur.getText())) {
            JOptionPane.showMessageDialog(null, "La duración debe ser un valor numérico que puede ser decimal");
        }
        else if (!esEntero(jTF_año.getText())) {
            JOptionPane.showMessageDialog(null, "El año de creación debe ser un valor numérico entero");
        }
        else { //añadir nueva canción
               //todo el texto se almacena en mayúsculas para evitar confusiones
           JOptionPane.showMessageDialog(null, gestionBD.añadirCancion(jTF_ide.getText().toUpperCase(),
                                                                      jTF_tit.getText().toUpperCase(),
                                                                      Double.parseDouble(jTF_dur.getText()),
                                                                      Integer.parseInt(jTF_año.getText()),
                                                                      jTF_gen.getText().toUpperCase(),
                                                                      autorSeleccionado
                                                                      ));
            dispose();
        }
        
        
    }//GEN-LAST:event_jButton_añadirActionPerformed

    private void jTF_ideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_ideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_ideActionPerformed

    private void jTF_genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_genActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_genActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCancionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCancionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCancionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCancionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new addCancionFrame().setVisible(true);
            }
        });
    }
    
    /**
     * Método que comprueba que el parámetro recibido es un valor decimal
     * @param texto
     * @return 
     */
    private boolean esDecimal(String texto) {
        try {
            Double.parseDouble(texto);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    /**
     * Método que comprueba que el parámetro recibido es un valor entero
     * @param texto
     * @return 
     */
    private boolean esEntero(String texto) {
        try {
            Integer.parseInt(texto);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    /**
     * Método que actualiza el Combo con los autores que hay en la base de datos
     */
    static void actualizarComboAutores(){
        ObjectSet autores = obtenerTodosAutores();
        jCombo_autores.removeAllItems();
        while (autores.hasNext()){
            Autor a = (Autor)autores.next();
            jCombo_autores.addItem(a.getNombre());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_añadir;
    private static javax.swing.JComboBox jCombo_autores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTF_año;
    private javax.swing.JTextField jTF_dur;
    private javax.swing.JTextField jTF_gen;
    private javax.swing.JTextField jTF_ide;
    private javax.swing.JTextField jTF_tit;
    // End of variables declaration//GEN-END:variables
}

